services:
  db:
    hostname: "dbcontainer"
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
    - 8306:3306
  flask:
    hostname: "web-app"
    build:
      context: .
      dockerfile: Dockerfile_flask
    ports:
    - 8000:80
    volumes:
    - ./flask_app:/opt/app